# uses Endpoints instead of creating a managed DNS zone. 
# Endpoints provides a free Google-managed DNS record for a public IP address.
swagger: "2.0"
info:
  description: "Cloud Endpoints DNS"
  title: "Cloud Endpoints DNS"
  version: "1.0.0"
paths: {}
host: "frontend.endpoints.phx-01h57q8t23amkhpscfjenrp9y2.cloud.goog"
x-google-endpoints:
- name: "frontend.endpoints.phx-01h57q8t23amkhpscfjenrp9y2.cloud.goog"
  target: "35.215.37.162"
