# loadbalancer cert
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: asm-ingress
spec:
  dnsNames:
    - frontend.endpoints.phx-01h57q8t23amkhpscfjenrp9y2.cloud.goog
  issuerRef:
    kind: ClusterIssuer
    # name: letsencrypt-staging
    name: selfsigned-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  secretName: tlskeys
---
